from dataclasses import asdict
from .rules import Finding


def markdown_report(requirements, quotations, findings: list[Finding]) -> str:
    critical = sum(f.severity == "CRITICAL" for f in findings)
    warning = sum(f.severity == "WARNING" for f in findings)
    lines = [
        "# Procurement Audit Report",
        "",
        f"**Vendors assessed:** {len(quotations)}  ",
        f"**Critical findings:** {critical}  ",
        f"**Warnings:** {warning}",
        "",
        "## Findings",
        "",
    ]
    if not findings:
        lines.append("No rule violations detected by the configured controls.")
    for n, f in enumerate(findings, 1):
        lines += [
            f"### {n}. [{f.severity}] {f.category} — {f.vendor} — {f.item}",
            "",
            f.message,
            "",
            "**Evidence:**",
        ]
        if f.evidence:
            for e in f.evidence:
                page = f" p.{e['page']}" if e.get("page") else ""
                quote = f" — {e['quote']}" if e.get("quote") else ""
                lines.append(f"- `{e['document']}`{page}{quote}")
        else:
            lines.append("- No source evidence attached.")
        lines.append("")

    lines += [
        "## Commercial Data",
        "",
        "| Vendor | Item | Qty | Unit Price | Currency | Delivery (days) | Warranty (months) |",
        "|---|---|---:|---:|---|---:|---:|",
    ]
    for q in quotations:
        for i in q.items:
            lines.append(f"| {q.vendor} | {i.item} | {i.quantity if i.quantity is not None else ''} | {i.unit_price if i.unit_price is not None else ''} | {i.currency or ''} | {i.delivery_days if i.delivery_days is not None else ''} | {i.warranty_months if i.warranty_months is not None else ''} |")
    lines += [
        "",
        "## Audit Method",
        "",
        "Numerical/control findings are generated by deterministic rules. Local LLM output, when used, is treated as extracted/normalized input and is not itself the final audit decision.",
    ]
    return "\n".join(lines)
